apiVersion: v1
kind: Service
metadata:
  name: crystal-backend
  namespace: crystal-erp
  labels:
    app.kubernetes.io/name: crystal-backend
    app.kubernetes.io/part-of: crystal-erp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: crystal-backend
