apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crystal-backend-uploads
  namespace: crystal-erp
  labels:
    app.kubernetes.io/name: crystal-backend
    app.kubernetes.io/part-of: crystal-erp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
