apiVersion: v1
kind: Service
metadata:
  name: crystal-frontend
  namespace: crystal-erp
  labels:
    app.kubernetes.io/name: crystal-frontend
    app.kubernetes.io/part-of: crystal-erp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: crystal-frontend
