apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crystal-erp

resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-pvc.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - migration-job.yaml

images:
  - name: crystal-backend
    newName: majeurbilly/crystal-backend
    newTag: latest
  - name: crystal-frontend
    newName: majeurbilly/crystal-frontend
    newTag: latest

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: crystal-erp
