apiVersion: v1
kind: Service
metadata:
  name: crystal-postgres
  namespace: crystal-erp
  labels:
    app.kubernetes.io/name: crystal-postgres
    app.kubernetes.io/part-of: crystal-erp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: crystal-postgres
