on:
  push:
    branches: [ "main", "dev" ]
    paths: [ "backend/*" ]
  workflow_dispatch:

env:
  buildConfiguration: "Release"
  solutionPath: "backend/"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      # 1. LINTER
      - name: "Lint: Dotnet Format"
        run: dotnet format ${{ env.solutionPath }} --verify-no-changes

      # 2. RESTORE & BUILD
      - name: Restore Dependencies
        run: dotnet restore ${{ env.solutionPath }}

      - name: Build Solution
        run: dotnet build ${{ env.solutionPath }} --configuration ${{ env.buildConfiguration }} --no-restore

      # 3. TESTS (Unit & Integration)
      - name: Run All Tests
        run: dotnet test ${{ env.solutionPath }} --configuration ${{ env.buildConfiguration }} --no-build --logger trx

      # 4. DOCKER IMAGE
      - name: Execute build-image.sh
        run: |
          chmod +x build-image.sh
          ./build-image.sh backend